### ISSUE TITLE
Error running the zookeeper.yml playbook

### ISSUE THREAD

**Issue by JNKHunter** [InsightDataScience/ansible-playbook#15]
Issuing the command:
```
ansible-playbook ./zookeeper.yml --extra-vars "zookeeper_tag=Name_insight-test" --tags install
```

yields the following error:
```
PLAY [Creating host group zookeeper from dynamic inventory] *******************************************************************

TASK [Gathering Facts] ********************************************************************************************************
ok: [localhost]

TASK [add_host] ***************************************************************************************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "'dict object' has no attribute u'tag_Name_insight_test'"}

NO MORE HOSTS LEFT ************************************************************************************************************
	to retry, use: --limit @/home/ubuntu/git/ansible-playbook/zookeeper.retry

PLAY RECAP ********************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1 
```

Here is the contents of my vars.yml file:

```
key_pair: ssh
instance_type: t2.medium
region: us-west-2
security_group_id: sg-7590d60e
num_instances: 2
subnet_id: subnet-1cd01347
tag_key_vals:
  Name: insight-test
  class: kafka
  class2: zookeeper
``` 
Any ideas if I'm doing something wrong or if a bug may be causing this?
